#pragma once

#ifndef IQTOOLS_PLUGIN_CONSTANTS_H
#define IQTOOLS_PLUGIN_CONSTANTS_H

#define IQTOOLS_PLUGIN_API_VERSION "1.0"
#define IQTOOLS_PLUGIN_API_VERSION_MAJOR 1
#define IQTOOLS_PLUGIN_API_VERSION_MINOR 0

#endif  // IQTOOLS_PLUGIN_CONSTANTS_H
